# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_gender',
            field=models.CharField(choices=[('FM', 'Female'), ('ML', 'Male')], default='ML', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_location',
            field=models.CharField(default='Any', editable=False, max_length=250),
        ),
    ]
