# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_auto_20171201_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_location',
            field=models.CharField(default='Any', max_length=250),
        ),
    ]
