# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0003_auto_20171201_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_pref_choice', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='interests',
            name='chosen_Interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_gender_pref',
            field=models.ManyToManyField(blank=True, to='userProfiles.GenderPreference'),
        ),
    ]
